language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

jdk:
  - oraclejdk8

notifications:
  email: false

install:
  - travis_wait 30 mvn install

before_script:
  - chmod +x gradlew
  - $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

script:
  - ./gradlew assemble check